### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by hugo411** [Hesto/multi-auth#55]
Hi, i am having 2 issues with the multi-auth.
I have a user and admin login (2 separate login pages).

1. When i am not logged as an admin and i want to access a page (example : admin/test123)
It redirect me to the user login and i am not sure where to look to correct that. I don't want my admins to fall into the user platform.

2. When i login as an admin, it sometimes redirect me to the user login too. The login is working fine because if i manually do /admin, i can see the admin index. It only happen the first time i try like something was saved into a cache. I don't know. 

Thanks!

**Comment by codepotato** [comment]
Hi @hugo411,

My guess here without seeing code is that the routes for the various pages are protected by middleware / guards and therefore require a user to be logged in as either an admin or user.

Did you solve this?

**Comment by hugo411** [comment]
You're right! In my controller i have a construct method that require the method to be guard('admin')
`  public function __construct()
    {
        $this->middleware('admin');
    }`
After removing that, it works but i am not sure if it is secure.

Thanks.

**Comment by codepotato** [comment]
@hugo411 You'll most likely need to protect the routes, but before we dive into that, are there any methods in your controller that should be accessible by the other type of user? If so, simply adding the $this->middleware() to the constructor will block everything from being visible by the other type of user. 

It might be that you need to protect each method individually, and in which case you might find it easier to do that from the routes file itself, rather than the controllers. 

Does that help? Let me know if you need any help.

**Comment by hugo411** [comment]
All the methods in that controller are for admin only so i had
`public function __construct() { $this->middleware('admin'); }`
But when i have this line, the admin login redirect me to user login.

Thanks for all the help.

**Comment by sakjawea** [comment]
hello there, my take for no.1 you might want to check the logic inside the admin middleware specifically if you have something like RedirectIfNotAdmin.php

for no.2 is it could be that the $redirectTo set in the admin login controller is pointing to a protected view by the middleware('auth'), 

good luck!
